<?php


/**
 * hook_node_view implementation
 */
function elis_moseschool_node_view($node,$view_mode,$langcode) {
  global $user;
  if ($node->type == "remote") {
    
    $field_remote_url = field_get_items('node', $node, 'field_remote_url');
    
    if ( $field_remote_url != false &&
      isset($field_remote_url[0]) && 
      isset($field_remote_url[0]['value']) &&
      preg_match("#^https?://uchebnik\.mos\.ru/.+#", $field_remote_url[0]['value'], $matches)
    ) 
    {
      $remote_id = false;
      $remoteUrl = $field_remote_url[0]['value'];
      $remotePlayerUrl = $remoteUrl;
      
      if (preg_match("#^https?://uchebnik\.mos\.ru/e?player\d?/books/([\d\.\w]+)/#",$field_remote_url[0]['value'],$matches)) {
        $remote_id = $matches[1];
      }
      if (preg_match("#^https?://uchebnik\.mos\.ru/app_player/(\d+)#",$field_remote_url[0]['value'],$matches)) {
        $remote_id = $matches[1];
        $remotePlayerUrl = str_replace("/catalogue/material_view/game_apps","/app_player",$remoteUrl);
      }
      if (preg_match("#^https?://uchebnik\.mos\.ru/composer\d?/document/([\d\.\w]+)/view#",$field_remote_url[0]['value'],$matches)) {
        $remote_id = $matches[1];
      }
      // atomics
      if (preg_match("#^https?://uchebnik\.mos\.ru/system_?\d?/atomic_objects/files/([\d\.\w\/]+)/(original)|(transcoded)/(.*)#",$field_remote_url[0]['value'],$matches)) {
        $remote_id = base64_encode($remoteUrl);
      }
      
      
      if ($remote_id !== false) {

        if ($view_mode == "full" && !isset($node->content['field_elis_player'])) {      
          $node->field_elis_player[LANGUAGE_NONE][0] = array("value"=>'');
          $node->content['field_elis_player'][0]['#markup'] = "";
        }

        if ($view_mode == 'full' && isset($node->content['field_elis_player'][0]['#markup'])) {
          if ($user->uid > 0) {

            $autologinUrl = $remotePlayerUrl;

            $doc_id = "node-iframe-id-" . $node->nid;
            $js = get_js_size_code_for_player_elis($doc_id);
            if (module_exists('elis_stats')) $js .= get_js_open_node_elis_stats($node);

            $button = '<a class="btn default btn-block" href="' . $autologinUrl . '" target="_blank"><i class="mdi-action-settings-overscan elis-control-icon"> Открыть на весь экран</i> </a>';
            if (isset($_GET['viewMode']) && $_GET['viewMode'] == 'embed') {            
              $button = '';
            }

            $output = $button . '<iframe id="' . $doc_id . '" style="width: 100%; height:100%; border: 0; visibility: hidden;" src="' . $autologinUrl . '"></iframe>';
            
            $reloadTimeout = 3000;
            $reloadString = '<script>setTimeout(function(){var iframe = document.getElementById("' . $doc_id . '"); iframe.src="' . $remotePlayerUrl .'"; iframe.style.visibility = "visible";}, ' . $reloadTimeout . ');</script>';
            
            if (isset($node->content['field_elis_player'][0]['#markup'])) {
              $node->content['field_elis_player'][0]['#markup'] = $output . $js . $reloadString;
            }
          } else {
            if (isset($node->content['field_elis_player'][0]['#markup'])) {
              $node->content['field_elis_player'][0]['#markup'] = "<div><strong>Для доступа к контенту необходимо авторизоваться.</strong></div>";
            }
          }
        }
      }
    }
  }
}

